apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qlswbsx2z-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qlswbsx2z-go 
  name: qlswbsx2z-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qlswbsx2z-go 
